FYP/FYP/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from recognition import views as recog_views
from employee import views as employee_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', recog_views.home, name='home'),
    
    path('dashboard/', recog_views.dashboard, name='dashboard'),
    path('train/', recog_views.train, name='train'),
    path('add_photos/', recog_views.add_photos, name='add-photos'),
    path('employees/', recog_views.employee_list, name='employee_list'),
    path('employees/<int:id>/edit/', recog_views.employee_edit, name='employee_edit'),
    path('employees/<int:id>/delete/', recog_views.employee_delete, name='employee_delete'),
    
    path('login/',auth_views.LoginView.as_view(template_name='employee/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='recognition/home.html'),name='logout'),
    path('register/', employee_views.register, name='register'),
    path('mark_your_attendance', recog_views.mark_your_attendance ,name='mark-your-attendance'),
    path('mark_your_attendance_out', recog_views.mark_your_attendance_out ,name='mark-your-attendance-out'),
    path('view_attendance_home', recog_views.view_attendance_home ,name='view-attendance-home'),
    path('export-attendance-csv/', recog_views.export_employee_attendance_csv, name='export_employee_attendance_csv'),
    path('export-attendance-csv/', recog_views.export_date_attendance_csv, name='export_date_attendance_csv'),
    
    path('view_attendance_date', recog_views.view_attendance_date ,name='view-attendance-date'),
    path('view_attendance_employee', recog_views.view_attendance_employee ,name='view-attendance-employee'),
    path('view_my_attendance', recog_views.view_my_attendance_employee_login ,name='view-my-attendance-employee-login'),
    path('not_authorised', recog_views.not_authorised, name='not-authorised'),
    
    path('calendar/', recog_views.calendar_view, name='calendar'),
    path('api/shifts/', recog_views.shifts_api, name='shifts_api'),
    path('add_shift/', recog_views.add_shift, name='add_shift'),
    path('edit_shift/<int:shift_id>/', recog_views.edit_shift, name='edit_shift'),
]

FYP/employee/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
import datetime

import datetime
# Create your models here.
	

class Present(models.Model):
    STATUS_CHOICES = [
        ('P', 'Present'),
        ('A', 'Absent'),
        ('L', 'Late'),
        ('E', 'Excused'),
    ]
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    present=models.BooleanField(default=False)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='A')
class Time(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	date = models.DateField(default=datetime.date.today)
	time=models.DateTimeField(null=True,blank=True)
	out=models.BooleanField(default=False)
class Shift(models.Model):
    SHIFT_CHOICES = (
        ('A', 'Shift A (04:00 - 12:00)'),
        ('B', 'Shift B (12:00 - 20:00)'),
        ('C', 'Shift C (20:00 - 04:00)'), 
        ('D', 'Day Off'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=True)
    shift_type = models.CharField(max_length=1, choices=SHIFT_CHOICES)
    start_time = models.TimeField(editable=False)
    end_time = models.TimeField(editable=False)

    def save(self, *args, **kwargs):
        # Define start and end times based on shift type
        shift_times = {
            'A': ('21:00:00', '05:00:00'),
            'B': ('05:00:00', '13:00:00'),
            'C': ('13:00:00', '21:00:00'),
        }
        times = shift_times.get(self.shift_type, ('00:00:00', '00:00:00'))
        self.start_time, self.end_time = times
        super().save(*args, **kwargs)
        
    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'
    
class ShiftCalendar(models.Model):
    users = models.ManyToManyField(User)  # Changed from ForeignKey to ManyToManyField
    date = models.DateField()
    shift_type = models.CharField(max_length=1, choices=[
        ('A', 'Shift A (04:00 - 12:00)'),
        ('B', 'Shift B (12:00 - 20:00)'),
        ('C', 'Shift C (20:00 - 04:00)'),
        ('D', 'Day Off')
    ])

    def __str__(self):
        user_names = ', '.join([user.username for user in self.users.all()])
        return f"{user_names} - {self.date} - {self.get_shift_type_display()}"

FYP/recognition/models.py
from django.db import models

# Create your models here.

FYP/recognition/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms
from employee.models import Shift, ShiftCalendar

#from django.contrib.admin.widgets import AdminDateWidget

class usernameForm(forms.Form):
	username=forms.CharField(max_length=30)

class DateForm(forms.Form):
	date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

class UsernameAndDateForm(forms.Form):
	username=forms.CharField(max_length=30)
	date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
	date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
 
class DateForm_2(forms.Form):
	date_from=forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
	date_to=forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
class ShiftEdit(forms.ModelForm):
    class Meta:
        model = Shift
        fields = ['shift_type']
        
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']
        
class ShiftForm(forms.ModelForm):
    class Meta:
        model = ShiftCalendar
        fields = ['users', 'date', 'shift_type']

    def __init__(self, *args, **kwargs):
        super(ShiftForm, self).__init__(*args, **kwargs)
        self.fields['users'].widget = forms.CheckboxSelectMultiple()
        self.fields['users'].queryset = User.objects.all()
        self.fields['date'].widget = forms.DateInput(attrs={'type': 'date'})

FYP/employee/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


#utility functions
'''
def hours_vs_date_every_employee():
	qs = Attendance.objects.all()
	diff=[]
	
	for obj in qs:
		ti=obj.time_in
		to=obj.time_out
		hours=((to-ti).total_seconds())/3600
		diff.append(hours)
		
	df = read_frame(qs)
	df['hours']=diff
	figure=plt.figure()
	sns.barplot(data=df,x='date',y='')
	html_graph=mpld3.fig_to_html(fig)


'''







# Create your views here.

@login_required
def register(request):
	if request.user.username!='admin':
		return redirect('not-authorised')
	if request.method=='POST':
		form=UserCreationForm(request.POST)
		if form.is_valid():
			form.save() ###add user to database
			messages.success(request, f'Employee registered successfully!')
			return redirect('dashboard')
		


	else:
		form=UserCreationForm()
	return render(request,'employee/register.html', {'form' : form})

FYP/recognition/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import usernameForm,DateForm,UsernameAndDateForm, DateForm_2, EmployeeForm, ShiftEdit, ShiftForm
from django.utils.dateparse import parse_time
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
import datetime as dt
from datetime import timedelta, date, datetime
from collections import defaultdict
import cv2
import dlib
import imutils
from imutils import face_utils
from imutils.video import VideoStream
from imutils.face_utils import rect_to_bb
from imutils.face_utils import FaceAligner
import time
from FYP.settings import BASE_DIR
import os
import face_recognition
from face_recognition.face_recognition_cli import image_files_in_folder
import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.svm import _classes
import numpy as np
from django.contrib.auth.decorators import login_required
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
from django_pandas.io import read_frame
from employee.models import Present, Time, Shift, ShiftCalendar
import seaborn as sns
import pandas as pd
from django.db.models import Count
#import mpld3
import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters
from matplotlib import rcParams
import math, csv

mpl.use('Agg')


#utility functions:
def username_present(username):
	if User.objects.filter(username=username).exists():
		return True
	
	return False

def create_dataset(username):
	id = username
	if(os.path.exists('face_recognition_data/training_dataset/{}/'.format(id))==False):
		os.makedirs('face_recognition_data/training_dataset/{}/'.format(id))
	directory='face_recognition_data/training_dataset/{}/'.format(id)

	# Detect face
	#Loading the HOG face detector and the shape predictpr for allignment

	print("[INFO] Loading the facial detector")
	detector = dlib.get_frontal_face_detector()
	predictor = dlib.shape_predictor('face_recognition_data/shape_predictor_68_face_landmarks.dat')   #Add path to the shape predictor ######CHANGE TO RELATIVE PATH LATER
	fa = FaceAligner(predictor , desiredFaceWidth = 300)
	#capture images from the webcam and process and detect the face
	# Initialize the video stream
	print("[INFO] Initializing Video stream")
	vs = VideoStream(src=0).start()
	#time.sleep(2.0) ####CHECK######

	# Our identifier
	# We will put the id here and we will store the id with a face, so that later we can identify whose face it is
	
	# Our dataset naming counter
	sampleNum = 0
	# Capturing the faces one by one and detect the faces and showing it on the window
	while(True):
		# Capturing the image
		#vs.read each frame
		frame = vs.read()
		#Resize each image
		frame = imutils.resize(frame ,width = 800)
		#the returned img is a colored image but for the classifier to work we need a greyscale image
		#to convert
		gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
		#To store the faces
		#This will detect all the images in the current frame, and it will return the coordinates of the faces
		#Takes in image and some other parameter for accurate result
		faces = detector(gray_frame,0)
		#In above 'faces' variable there can be multiple faces so we have to get each and every face and draw a rectangle around it.
		
		
		for face in faces:
			print("inside for loop")
			(x,y,w,h) = face_utils.rect_to_bb(face)
			face_aligned = fa.align(frame,gray_frame,face)
			# Whenever the program captures the face, we will write that is a folder
			# Before capturing the face, we need to tell the script whose face it is
			# For that we will need an identifier, here we call it id
			# So now we captured a face, we need to write it in a file
			sampleNum = sampleNum+1
			# Saving the image dataset, but only the face part, cropping the rest
			
			if face is None:
				print("face is none")
				continue
			cv2.imwrite(directory+'/'+str(sampleNum)+'.jpg'	, face_aligned)
			face_aligned = imutils.resize(face_aligned ,width = 400)
			#cv2.imshow("Image Captured",face_aligned)
			# @params the initial point of the rectangle will be x,y and
			# @params end point will be x+width and y+height
			# @params along with color of the rectangle
			# @params thickness of the rectangle
			cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),1)
			# Before continuing to the next loop, I want to give it a little pause
			# waitKey of 100 millisecond
			cv2.waitKey(50)

		#Showing the image in another window
		#Creates a window with window name "Face" and with the image img
		cv2.imshow("Add Images",frame)
		#Before closing it we need to give a wait command, otherwise the open cv wont work
		# @params with the millisecond of delay 1
		cv2.waitKey(1)
		#To get out of the loop
		if(sampleNum>200):
			break
	
	#Stoping the videostream
	vs.stop()
	# destroying all the windows
	cv2.destroyAllWindows()
	file_path = os.path.join(directory, '1.jpg')
	if os.path.exists(file_path):
		os.remove(file_path)
		print(f"Deleted file: {file_path}")
	else:
		print(f"File not found: {file_path}")



def predict(face_aligned,svc,threshold=0.7):
	face_encodings=np.zeros((1,128))
	try:
		x_face_locations=face_recognition.face_locations(face_aligned)
		faces_encodings=face_recognition.face_encodings(face_aligned,known_face_locations=x_face_locations)
		if(len(faces_encodings)==0):
			return ([-1],[0])
	except:
		return ([-1],[0])
	prob=svc.predict_proba(faces_encodings)
	result=np.where(prob[0]==np.amax(prob[0]))
	if(prob[0][result[0]]<=threshold):
		return ([-1],prob[0][result[0]])
	return (result[0],prob[0][result[0]])


def vizualize_Data(embedded, targets,):
	
	X_embedded = TSNE(n_components=2).fit_transform(embedded)
	for i, t in enumerate(set(targets)):
		idx = targets == t
		plt.scatter(X_embedded[idx, 0], X_embedded[idx, 1], label=t)
	plt.legend(bbox_to_anchor=(1, 1));
	rcParams.update({'figure.autolayout': True})
	plt.tight_layout(pad=3.0)	
	plt.savefig('./recognition/static/recognition/img/training_visualisation.png')
	plt.close()


def update_attendance_in_db_in(present):
	today=dt.date.today()
	time=dt.datetime.now()
	for person in present:
		user=User.objects.get(username=person)
		try:
			qs=Present.objects.get(user=user,date=today)
		except:
			qs= None

		if qs is None:
			if present[person]==True:
						a=Present(user=user,date=today,present=True)
						a.save()
			else:
				a=Present(user=user,date=today,present=False)
				a.save()
		else:
			if present[person]==True:
				qs.present=True
				qs.save(update_fields=['present'])
		if present[person]==True:
			a=Time(user=user,date=today,time=time, out=False)
			a.save()


def update_attendance_in_db_out(present):
	today=dt.date.today()
	time=dt.datetime.now()
	for person in present:
		user=User.objects.get(username=person)
		if present[person]==True:
			a=Time(user=user,date=today,time=time, out=True)
			a.save()


def check_validity_times(times_all):

	if(len(times_all)>0):
		sign=times_all.first().out
	else:
		sign=True
	times_in=times_all.filter(out=False)
	times_out=times_all.filter(out=True)
	if(len(times_in)!=len(times_out)):
		sign=True
	break_hourss=0
	if(sign==True):
			check=False
			break_hourss=0
			return (check,break_hourss)
	prev=True
	prev_time=times_all.first().time

	for obj in times_all:
		curr=obj.out
		if(curr==prev):
			check=False
			break_hourss=0
			return (check,break_hourss)
		if(curr==False):
			curr_time=obj.time
			to=curr_time
			ti=prev_time
			break_time=((to-ti).total_seconds())/3600
			break_hourss+=break_time

		else:
			prev_time=obj.time

		prev=curr

	return (True,break_hourss)


def convert_hours_to_hours_mins(hours):
	
	h=int(hours)
	hours-=h
	m=hours*60
	m=math.ceil(m)
	return str(str(h)+ " hrs " + str(m) + "  mins")


#used
def hours_vs_date_given_employee(present_qs, time_qs, admin=True):
    register_matplotlib_converters()
    df_hours = []
    df_break_hours = []
    qs = present_qs

    for obj in qs:
        date = obj.date
        obj.user_shift = Shift.objects.filter(user=obj.user).first()
        if not obj.user_shift:
            print(f"No shift assigned for user {obj.user}")
            continue
        
        times_in = time_qs.filter(date=date, out=False).order_by('time')
        times_out = time_qs.filter(date=date, out=True).order_by('time')
        times_all = time_qs.filter(date=date).order_by('time')

        obj.time_in = times_in.first().time if times_in.exists() else None
        obj.time_out = times_out.last().time if times_out.exists() else None

        if obj.time_in:
            obj.shift_start_time = obj.user_shift.start_time
            if obj.time_in.time() > obj.shift_start_time:
                obj.status = 'L'  
            else:
                obj.status = 'P' 
            obj.save()

        if obj.time_in and obj.time_out:
            ti = obj.time_in
            to = obj.time_out
            hours = (to - ti).total_seconds() / 3600
            obj.hours = hours
            obj.shift_end_time = obj.user_shift.end_time
            if obj.hours < 8:
                obj.status = 'E' 
                obj.save()
        else:
            obj.hours = 0
            
        df_hours.append(obj.hours)

        obj.hours = convert_hours_to_hours_mins(obj.hours)

    df = read_frame(qs)
    df["hours"] = df_hours

    print(df)
    
    sns.barplot(data=df, x='date', y='hours')
    plt.title('Number of hours worked each day')
    plt.xticks(rotation='vertical')
    rcParams.update({'figure.autolayout': True})
    plt.tight_layout()
    
    if admin:
        plt.savefig('./recognition/static/recognition/img/attendance_graphs/hours_vs_date/1.png')
    else:
        plt.savefig('./recognition/static/recognition/img/attendance_graphs/employee_login/1.png')
    plt.close()

    return qs
	

#used
def hours_vs_employee_given_date(present_qs,time_qs):
	register_matplotlib_converters()

FYP/recognition/templates/recognition/add_photos.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <style>
        body {
            background: url('{% static "recognition/img/bg_image.jpg" %}') no-repeat center center fixed;
            background-size: cover;
        }

        .overlay {
            background: rgba(0, 0, 0, 0.6);
            padding: 2em;
            color: #fff;
            border-radius: 10px;
            box-shadow: 2px 2px 15px rgba(0, 3, 0, 0.7);
            margin: 50px auto;
        }

        .header {
            background: rgba(0, 0, 0, 0.6);
            padding: 1em 0;
            color: #fff;
            border-radius: 10px;
            box-shadow: 2px 2px 15px rgba(0, 3, 0, 0.7);
            margin: 20px auto;
            text-align: center;
        }

        .alert-container {
            padding-top: 20px;
        }
    </style>
</head>
<body>

    <div class="header">
        <a href="{% url 'dashboard' %}" class="text-white"><h5>Back</h5></a>
    </div>

    <div class="col-lg-4 overlay">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Enter Employee's Name</legend>
                {{ form|crispy }}
            </fieldset>

            <div class="form-group text-center">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>

    <div class="col-lg-12 alert-container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

FYP/recognition/templates/recognition/add_shift.html
{% block content %}
<style>
    /* Basic styling for the form */
    .form-container {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        background-color: #f9f9f9;
        border-radius: 5px;
        border: 1px solid #ccc;
    }

    /* Flexbox to align labels and fields on the same row */
    .form-row {
        display: flex;
        align-items: center; /* Aligns items vertically in the center */
        margin-bottom: 10px;
    }

    .form-row label {
        flex: 0 0 20%; /* Flex grow, flex shrink, flex basis */
        margin-right: 10px;
    }

    .form-row .input-field {
        flex: 1; /* Take up the remaining space */
    }

    button, .link-button {
        padding: 10px;
        margin-top: 10px;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
        text-align: center;
        display: inline-block;
        text-decoration: none; /* Removes underline from links styled as buttons */
    }

    button:hover {
        background-color: #0056b3;
    }
    .link-button {
        background-color: #6c757d; /* Different color for less priority action */
    }
</style>

<div class="form-container">
    <a href="{% url 'calendar' %}" class="link-button">Back to Calendar</a>
    <h2>Add Shift</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-row">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            <div class="input-field">
                {{ field }}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        <button type="submit">Add Shift</button>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Focus the first input field in the form
        const firstInput = document.querySelector('.form-container input');
        if (firstInput) {
            firstInput.focus();
        }
    });
</script>
{% endblock %}

FYP/recognition/templates/recognition/calendar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@latest/main.min.css" rel="stylesheet">
    <style>
        h1 {
            text-align: center; /* Ensures the heading is centered */
            color: #333; /* Sets a dark gray color for the text */
            font-family: 'Arial', sans-serif; /* Uses Arial font for the heading */
        }
        .fc-event-title, .fc-event-title-container {
            white-space: normal; /* Allows text to wrap */
        }
        .fc-event-main-frame {
            padding: 2px 4px; /* Add some padding inside the event for better readability */
        }
        /* Ensure text color is black for better contrast */
        .fc-event-title-container {
            color: black; /* Set text color to black */
        }
        #link-container {
            text-align: right; /* Aligns content to the right */
            margin-bottom: 10px; /* Adds space below the link */
        }
        a.button-style {
            display: inline-block; /* Allows width and padding to be adjusted */
            padding: 10px 20px; /* Padding inside the button */
            background-color: #007BFF; /* Bootstrap primary blue */
            color: white; /* White text color */
            text-decoration: none; /* Removes underline from the link */
            border-radius: 5px; /* Rounded corners for the button */
            transition: background-color 0.3s, transform 0.2s; /* Smooth background color and transform transitions */
        }
        a.button-style:hover, a.button-style:focus {
            background-color: #0056b3; /* Darker blue on hover/focus */
            transform: translateY(-2px); /* Slight raise effect on hover/focus */
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@latest/main.min.js"></script>
</head>
<body>
    <h1 id="shiftCalendar">Shift Calendar</h1>
    <div id="link-container">
        <a href="{% url 'dashboard' %}" class="button-style">Back to Dashboard</a>
    </div>
        <div id="calendar"></div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                events: '/api/shifts/',
                eventClick: function(arg) {
                    window.location.href = `/edit_shift/${arg.event.id}`;
                },
                dateClick: function(info) {
                    // Redirect to a URL to add a shift for the clicked date
                    window.location.href = `/add_shift?date=${info.dateStr}`;
                },
                eventContent: function(arg) {
                    var element = document.createElement('div');
                    element.classList.add('fc-event-title-container');
                    element.innerHTML = `<b>${arg.event.title}</b>`;
                    element.style.backgroundColor = arg.event.extendedProps.color; // Apply background color
                    element.style.color = 'black'; // Ensure text color is black
                    return { domNodes: [element] };
                }
            });
            calendar.render();
        });
    </script>
</body>
</html>

FYP/recognition/templates/recognition/employee_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Confirmation</title>
</head>
<body>
    <h1>Are you sure you want to delete {{ employee.username }}?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
        <a href="{% url 'employee_list' %}">Cancel</a>
    </form>
</body>
</html>

FYP/recognition/templates/recognition/employee_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Employee List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f4f4f9;
            color: #333;
        }
        .header {
            display: flex;
            justify-content: space-between; /* Aligns items on the main-axis */
            align-items: center; /* Aligns items on the cross-axis */
        }
        h1 {
            color: #0066cc;
            margin: 0; /* Removes default margin */
        }
        ul {
            list-style: none;
            padding: 0;
        }
        li {
            background-color: #fff;
            border: 1px solid #ddd;
            padding: 10px 15px;
            margin-bottom: 10px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        a {
            color: #0077cc;
            text-decoration: none;
            font-weight: bold;
            margin-left: 10px;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Employee List</h1>
        <a class="nav-link" href="{% url 'view-attendance-home' %}">Back to Attendance Dashboard</a>
    </div>
    <ul>
        {% for employee in employees %}
            <li>
                {{ employee.username }} - {{ employee.email }}
                {% for shift in employee.shift_set.all %}
                    - {{ shift.get_shift_type_display }}
                {% empty %}
                    - No shift assigned
                {% endfor %}
                <a href="{% url 'employee_edit' id=employee.id %}">Edit</a>
                <a href="{% url 'employee_delete' id=employee.id %}">Delete</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>